### PR TITLE
API & Framework changes

### LINKED ISSUE #7: Add interactivity for Windows
Following are the effected Renderable objects:
- [x] Image
- [x] Plot
- [x] Histogram
- [x] Plot3
- [x] Surface

### LINKED ISSUE #41: ArrayFire event handling
Will event handlers, like mouse click, mouse drag, scrolling, etc. be integrated to ArrayFire?

### LINKED ISSUE #48: Handling Multiple Plots and Different draw calls per one chart
We can discuss the different possible directions in which we want to implement the current issue. Please post the URLS to other plotting libraries for reference.

### LINKED ISSUE #75: Font glyph packing
Early version maintained individual textures for each character glyph, which was very inefficient.

Pack the glyphs into a single texture.

### LINKED ISSUE #76: Support to save framebuffer as bmp or png

### LINKED ISSUE #80: histogram_opencl example color bars not unique, only last bar updates
The `histogram_opencl` example appears to have two bugs:

1. The color of the bars is always yellow and
2. Between successive frames only the last bar ever updates

See screenshots below.

Appearance of `histogram_cuda` shows bars that are in different colors and they all update their value every frame. This is the correct behavior.
screenshot from 2016-03-03 11-21-55

whereas `histogram_opencl` shows bars that are all yellow in color and only the last bar updates between successive frames:

### LINKED ISSUE #81: histogram example is incorrect
There are (at least) two issues here with the histogram example:

1. The Perlin distribution should result in a Gaussian-like distribution of noise, whereas the histogram does not display anything remotely close to this, and 
2. There appears to be a plotting error wherein every 3n and 4n  values are near zero in the histogram.

The Perlin distribution used  in the histograms should [result in a Gaussian-like noise distribution](http://stackoverflow.com/questions/9549851/uniform-distribution-from-a-fractal-perlin-noise-function-in-c-sharp); however, in the examples, it is anything but Gaussian:

5a349626-e132-11e5-9654-ed3c3b8d0596

This is even more apparent if one increases the number of bins to around 100:

screenshot from 2016-03-03 13-08-41

Also, there appears to be an odd pattern wherein every 3rd and 4th value on the x-axis is near zero.

### PR DESCRIPTION
**Pull request by 9prady9**
Includes the following:
- [x] Automatic conversion of GLSL shader files to c++ source strings for shader compilation.
- [x] Support for rendering multiple plots per chart. Fixes #48 
- [x] Interactivity support for renderings. Fixes #7 
- [x] Alignment corrections for chart axes labels and tick labels
- [x] Per vertex attributes (colors, alpha values, marker sizes - scatter plots) support 
- [x] Alpha blending support for all renderings
- [x] Update README with pictures of different renderables
- [x]  Pack font glyphs. Fixes #75 
- [x] Added grid lines for 2d & 3d charts along ticks for better visibility/understanding of plot points.
- [x] Support for saving framebuffer programmatically. Fixes #76 
- [x] C-API
- [x] Reorganized code to enable easy addition of new rendering backends.
- [x] Fixes #81 
- [x] Fixes #80

### CODE REVIEW

File: src/common.hpp [hunk 1]
```diff
@@ -9,16 +9,125 @@
...
+
 #include <vector>
 
-static const float GRAY[]  = {0.0f   , 0.0f   , 0.0f   , 1.0f};
-static const float WHITE[] = {1.0f   , 1.0f   , 1.0f   , 1.0f};
-static const float BLUE[]  = {0.0588f, 0.1137f, 0.2745f, 1.0f};
-static const float RED[]   = {1.0f   , 0.0f   , 0.0f   , 1.0f};
+static const float BLACK[]   = {0.0f    , 0.0f    , 0.0f    , 1.0f};
+static const float GRAY[]    = {0.85f   , 0.85f   , 0.85f   , 1.0f};
+static const float PEARL[]   = {1.0f    , 1.0f    , 1.0f    , 1.0f};
```
Comment (shehzan10) [inline src/common.hpp]: Why is the pearl and not white?

Comment (pavanky) [inline src/common.hpp]: Good question, what the hell is pearl ?

Comment (9prady9) [inline src/common.hpp]: Just a residue from old commit, will change the name to white.

File: examples/cpu/fractal.cpp [hunk 2]
```diff
@@ -42,9 +42,9 @@ int main(void)
      * it can be used for rendering text */
     fg::Font fnt;
 #ifdef OS_WIN
-    fnt.loadSystemFont("Calibri", 32);
+    fnt.loadSystemFont("Calibri");
 #else
-    fnt.loadSystemFont("Vera", 32);
+    fnt.loadSystemFont("Vera");
 #endif
```
Comment (pavanky) [inline examples/cpu/fractal.cpp]: We are not including these fonts are we ?

File: examples/cpu/plotting.cpp [hunk 3]
```diff
@@ -47,40 +55,38 @@ int main(void){
      * it can be used for rendering text */
     fg::Font fnt;
 #ifdef OS_WIN
-    fnt.loadSystemFont("Calibri", 32);
+    fnt.loadSystemFont("Calibri");
 #else
-    fnt.loadSystemFont("Vera", 32);
+    fnt.loadSystemFont("Vera");
```
Comment (pavanky) [inline examples/cpu/plotting.cpp]: Can't we have this as a default option for `wnd` ? This way we don't have to set it every time.

File: include/CPUCopy.hpp [hunk 4]
```diff
@@ -22,19 +22,14 @@ void copy(fg::Image& out, const T * dataPtr)
...
- * `unsigned Renderable::size() const;`
- *
- * Currently fg::Plot, fg::Histogram objects in Forge library fit the bill
+ * Below functions expects OpenGL resource Id and size in bytes to copy the data from
+ * cpu memory location to graphics memory
  */
-template<class Renderable, typename T>
-void copy(Renderable& out, const T * dataPtr)
+template<typename T>
+void copy(const int resourceId, const size_t resourceSize, const T * dataPtr)
```
Comment (pavanky) [inline include/CPUCopy.hpp]: I am not sure why this needs to be a template (unless you are asserting the data type to be the same as the one inside `resourceId`). If not it should be removed from all the places and use `void *` instead.

File: include/CUDACopy.hpp [hunk 5]
```diff
@@ -43,20 +43,15 @@ void copy(fg::Image& out, const T * devicePtr)
...
  */
-template<class Renderable, typename T>
-void copy(Renderable& out, const T * devicePtr)
+template<typename T>
+void copy(const int resourceId, const T * devicePtr)
 {
     cudaGraphicsResource *cudaVBOResource;
-    CUDA_ERROR_CHECK(cudaGraphicsGLRegisterBuffer(&cudaVBOResource, out.vbo(), cudaGraphicsMapFlagsWriteDiscard));
-
+    CUDA_ERROR_CHECK(cudaGraphicsGLRegisterBuffer(&cudaVBOResource, resourceId,
```
Comment (pavanky) [inline include/CUDACopy.hpp]: Rename this macro to be `FORGE_CUDA_CHECK` or something along those lines so it won't conflict with user defined macros.

File: include/OpenCLCopy.hpp [hunk 6]
```diff
@@ -28,25 +29,21 @@ static void copy(fg::Image& out, const cl::Buffer& in, const cl::CommandQueue& q
...
 /*
- * Below functions takes any renderable forge object that has following member functions
- * defined
- *
- * `unsigned Renderable::vbo() const;`
- * `unsigned Renderable::size() const;`
- *
- * Currently fg::Plot, fg::Histogram objects in Forge library fit the bill
+ * Below functions expects OpenGL resource Id and size in bytes to copy the data from
+ * OpenCL Buffer to graphics memory
```
Comment (pavanky) [inline include/OpenCLCopy.hpp]: Implement versions where `cl.hpp` is not included as well.

File: include/fg/chart.h [hunk 7]
```diff
@@ -0,0 +1,191 @@
...
+#include <fg/defines.h>
+#include <fg/image.h>
+#include <fg/plot.h>
+#include <fg/surface.h>
+#include <fg/histogram.h>
+
+#include <string>
+#include <vector>
+
+namespace internal
```
Comment (pavanky) [inline include/fg/chart.h]: This is a bad name for a name space. it should either be nested inside `forge` or just use `void *` instead of _Chart.

Also considering that it is inside a different namespace, why the `_` ?

File: include/fg/chart.h [hunk 8]
```diff
@@ -0,0 +1,191 @@
...
+        FGAPI ~Chart();
+
+        /**
+           Set axes titles for the chart
+
+           \param[in] pX is x-axis title label
+           \param[in] pY is y-axis title label
+           \param[in] pZ is z-axis title label
+         */
+        FGAPI void setAxesTitles(const std::string pX,
```
Comment (pavanky) [inline include/fg/chart.h]: @umar456 is this safe ? I remember you mentioning something about C++ classes changing between implementations. Would this cause an issue ?

File: include/fg/defines.h [hunk 9]
```diff
@@ -47,6 +47,10 @@
  */
 FGAPI GLEWContext* glewGetContext();
 
+typedef unsigned int    uint;
+typedef unsigned short  ushort;
+typedef unsigned char   uchar;
```
Comment (pavanky) [inline include/fg/defines.h]: Put them inside namespace.

File: include/fg/histogram.h [hunk 10]
```diff
@@ -19,14 +19,16 @@ class _Histogram;
...
 /**
    \class Histogram
 
-   \brief Bar graph to display data frequencey.
+   \brief Histogram is a bar graph to display data frequencey.
  */
 class Histogram {
     private:
-        internal::_Histogram* value;
+        internal::_Histogram* mValue;
```
Comment (pavanky) [inline include/fg/histogram.h]: Try to remove the underscore.

**Comment by pavanky** [comment]
@9prady9 try to remove STL classes from the API. If you want to use them, implement them inside the header itself. This will ensure the implementation of the objects in the compiled version and the headers match.

File: examples/cpu/fractal.cpp (hunk 2 above)
Comment (9prady9) [inline examples/cpu/fractal.cpp]: No, we are not currently including these. Vera family is one of the most common font families available on Unix/Linux systems. Similarly, Calibri on Windows. I don't think we need to include them unless there is a possibility of these fonts missing on these systems.

File: include/CPUCopy.hpp (hunk 4 above)
Comment (9prady9) [inline include/CPUCopy.hpp]: Yes, we can do that.

File: examples/cpu/plotting.cpp (hunk 3 above)
Comment (9prady9) [inline examples/cpu/plotting.cpp]: Sure, we can use a default font setup internally that is replaced if user explicitly asks for it.

File: include/fg/chart.h (hunk 7 above)
Comment (9prady9) [inline include/fg/chart.h]: I can move `internal` namespace inside `fg`. If we make `void*` to store class objects, we would have to do `reinterpret_cast` or some sort of casting operation to corresponding class type inside each member function before delegating the call to the corresponding upstream object. Do you have any suggestions for new name to `internal` namespace ?

Regarding `_`: I have been following that convention since the inception. There are three layers in the call delegation starting from the API level to implementation level. It is an easy visual cue as to which layer this object corresponds to and also removes the need to use namespace if both objects are of same name. Using scope resolution results in use of `2+len(namespace)` additional characters instead of just one each time object of this  layer is used. I would like to retain this visual cue, it has proved to be useful.

File: include/OpenCLCopy.hpp (hunk 6 above)
Comment (9prady9) [inline include/OpenCLCopy.hpp]: Sure, but I will add those versions while adding C-API.

Comment (9prady9) [inline include/OpenCLCopy.hpp]: C-API is added now.

**Comment by shehzan10** [comment]
Since we are adding freeimage, any thoughts on having a function that loads and displays the image in a single call?

**Comment by shehzan10** [comment]
I notice that the C++ classes do not have constructors that accept the c-style struct pointers. I think this should be available.

**Comment by shehzan10** [comment]
I think font management should be a manager. There should be a map between the fonts loaded and the handle. If there is a constant loading of different fonts, that can be a big issue.

**Comment by shehzan10** [comment]
General concerns/clarifications:
* The fg_* display typedefs (window, chart etc), are all typedefs to `void*`. I'm a little concerned about how much they'll be abused.
* The `getDisplay(fg_display *)` functions do not check if the inputs are valid pointers. I think this can be resolved if we have a display manager of sorts that handles the pointers etc.
* A lot of functions such as set positions, axes, limits, colors etc are not being checked for value ranges. Is there merit in checking these?
* Any reason why we are implementing the `src/backend/*.hpp` classes in the header files?
* I don't like having 2 different typedefs for uint etc in namespace fg and internal. Might as well typedef internal names to the fg ones, ie `typedef fg::type internal::type`

**Comment by 9prady9** [comment]
Replying here since original comment is cluttered with others above.

Regarding the following comments by @shehzan10 
```
I notice that the C++ classes do not have constructors that accept the c-style 
handles. I think this should be available.
```
Sure we can add them,  makes the code in api files more terse.

```
Since we are adding freeimage, any thoughts on having a function that loads 
and displays the image in a single call?
```
Forge so far has been object centric, you need a window to render something. Have a function such as below
```
displaImage(...)
```
would require us to keep state (internally maintain a Window) to display any image that gets passed into the above function.

**Comment by shehzan10** [comment]
I'm not onboard with implementing classes in the backend/*.hpp files in the header, especially the constructors.
Also, I've noticed most of them (histogram, plot, chat etc) return the same member variables etc in the function. Why not just use a derived class? All of them seem to have very similar members.

**Comment by 9prady9** [comment]
@shehzan10 Regarding using inheritance at the `common` namespace level for renderable objects, didn't occur to me until you pointed it out. Let me see how we can do it with least code duplication. If you have already thought it out, please post it here.

**Comment by shehzan10** [comment]
I haven't thought of a specific design. But you can essentially put all the common stuff in the interface and then derive that. I guess ArrayInfo or MemoryManager classes in ArrayFire are a good place to look.

**Comment by 9prady9** [comment]
@pavanky @shehzan10 Okay, i fixed the cuda and opencl examples. Please run them on your machines and let me know if any issues are there. I will move to trying `glbinding` now.

File: include/fg/defines.h [hunk 11]
```diff
@@ -47,10 +47,19 @@
...
+typedef void* fg_histogram;
+typedef void* fg_plot;
+typedef void* fg_surface;
+
+typedef unsigned int    uint;
+typedef unsigned short  ushort;
+typedef unsigned char   uchar;
+
+typedef enum {
     FG_SUCCESS            = 0,              ///< Fuction returned successfully.
```
Comment (pavanky) [inline include/fg/defines.h]: I like the idea of having `FG_ERR_NONE` as opposed to `FG_SUCCESS` (or at least have both) for consistency reasons.

File: include/fg/defines.h [hunk 12]
```diff
@@ -96,23 +116,28 @@ enum ErrorCode {
...
     FG_RG        = 200,                     ///< Three(Red, Green & Blue) channels
     FG_RGB       = 300,                     ///< Three(Red, Green & Blue) channels
     FG_BGR       = 301,                     ///< Three(Red, Green & Blue) channels
     FG_RGBA      = 400,                     ///< Four(Red, Green, Blue & Alpha) channels
     FG_BGRA      = 401                      ///< Four(Red, Green, Blue & Alpha) channels
-};
+} fg_channel_format;
+
+typedef enum {
+    FG_2D = 2,                              ///< Two dimensional charts
```
Comment (pavanky) [inline include/fg/defines.h]: `FG_CHART_XY`

File: include/fg/defines.h [hunk 13]
```diff
@@ -120,9 +145,9 @@ enum ColorMap {
     FG_MOOD_MAP     = 4,                    ///< Mood color map
     FG_HEAT_MAP     = 5,                    ///< Heat color map
     FG_BLUE_MAP     = 6                     ///< Blue color map
-};
+} fg_color_map;
```
Comment (pavanky) [inline include/fg/defines.h]: `FG_MAP_FOO` instead of `FG_FOO_MAP` ?

File: include/fg/defines.h [hunk 14]
```diff
@@ -141,23 +166,36 @@ enum dtype {
...
-    FG_POINT        = 1,
-    FG_CIRCLE       = 2,
-    FG_SQUARE       = 3,
-    FG_TRIANGLE     = 4,
-    FG_CROSS        = 5,
-    FG_PLUS         = 6,
-    FG_STAR         = 7
-};
-
+} fg_dtype;
```
Comment (pavanky) [inline include/fg/defines.h]: This will class with arrayfire, there is no reason to have them use the same enums.

File: include/fg/defines.h [hunk 15]
```diff
@@ -141,23 +166,36 @@ enum dtype {
...
+
+typedef enum {
+    FG_LINE         = 0,                    ///< Line plot
+    FG_SCATTER      = 1,                    ///< Scatter plot
+    FG_SURFACE      = 2                     ///< Surface plot
+} fg_plot_type;
```
Comment (pavanky) [inline include/fg/defines.h]: `FG_PLOT_XYZ`

File: include/fg/defines.h [hunk 16]
```diff
@@ -141,23 +166,36 @@ enum dtype {
...
+typedef enum {
+    FG_NONE         = 0,                    ///< No marker
+    FG_POINT        = 1,                    ///< Point marker
+    FG_CIRCLE       = 2,                    ///< Circle marker
+    FG_SQUARE       = 3,                    ///< Square marker
+    FG_TRIANGLE     = 4,                    ///< Triangle marker
+    FG_CROSS        = 5,                    ///< Cross-hair marker
+    FG_PLUS         = 6,                    ///< Plus symbol marker
+    FG_STAR         = 7                     ///< Star symbol marker
+} fg_marker_type;
```
Comment (pavanky) [inline include/fg/defines.h]: `FG_MARKER_XYZ`

File: include/fg/font.h [hunk 17]
```diff
@@ -10,10 +10,24 @@
...
 #include <fg/defines.h>
 
-namespace internal
-{
-class _Font;
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+FGAPI fg_err fg_create_font(fg_font* pFont);
```
Comment (pavanky) [inline include/fg/font.h]: What does `pFont` contain on exit ?

Comment (pavanky) [inline include/fg/font.h]: If it is loading default font, why not say that then ? `fg_load_default_font`

File: include/fg/histogram.h [hunk 18]
```diff
@@ -11,10 +11,40 @@
...
-{
-class _Histogram;
+
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+FGAPI fg_err fg_create_histogram(fg_histogram *pHistogram,
+                                 const uint nbins, const fg_dtype type);
+
```
Comment (pavanky) [inline include/fg/histogram.h]: What about the axes ranges ?

Comment (9prady9) [inline include/fg/histogram.h]: what about them ?

File: include/fg/font.h (hunk 17 above)
Comment (9prady9) [inline include/fg/font.h]: C-API doesn't have any documentation. I will do another round for that once the functionality is working.

It doesn't load any default font with just create call, again that will be clear once i update it with documentation. `pFont` is only used if `fg_create_font` is called upon, otherwise it is an irrelevant variable.

**Comment by 9prady9** [comment]
@pavanky Finished types enum changes we have discussed, PR is ready now.
